#!/bin/sh
set -e
lb config noauto --mode debian --distribution bookworm --architectures amd64 --archive-areas "main contrib non-free non-free-firmware" --binary-images iso-hybrid --build-with-chroot false --bootloader syslinux --debian-installer false --memtest none --iso-application "Clarity OMR Appliance" --iso-publisher "Local build" --iso-volume CLARITY_OMR --security false --bootappend-live "boot=live components quiet splash noeject hostname=clarity-omr username=appliance" "${@}"
